### PR TITLE
Adds various build artifacts to the git ignore list

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by r0mai** [comment]
I wouldn't merge this. According to the docs you're supposed to do the build from the `bin/` directory, and everything under `bin/` is already ignored.

**Comment by jonesmz** [comment]
I'm fine with you closing the pull request.

Though, in my personal opinion, no one is going to read the documentation for how to compile a program that uses cmake, unless they can't get the program to compile by simply doing

"cmake . && make"

Since that works without any error messages, the majority of potential one-off contributors (such as myself) are going to see a bunch of build files scattered around.


My recommendation is that if you are serious about only running cmake targeted at "bin", put in a warning or error to indicate that.

**Comment by r0mai** [comment]
I understand your argument but this is something that is very difficult to maintain IMO.

We would have to ignore:
* new build artifacts (which we won't notice since we use out of tree builds under `bin`)
* the project files for all kinds of build systems: make, ninja, VS, xcode, etc... Also not something that I would want to maintain.

I agree that experienced developers won't read the docs if it just works. I personally always compile cmake projects out of tree by default. It's just trivial to clean up after yourself and you won't pollute the repository like this.

`mkdir -p bin && cd bin && cmake .. && make`

Of course @sabel83 has the final word.

**Comment by jonesmz** [comment]
Sure, one way or another, it doesn't matter to me. I simply noticed the build artifacts while working on a Gentoo ebuild and figured it was easy enough to make a pull request.

**Comment by sabel83** [comment]
Thank you for the pull request, however, as r0mai mentioned, the list is platform and build system dependent. Displaying a warning (referring to the git issue) when not building in `bin` is a good idea (we should probably do it at some point).

**Pull request closed without merging**
