### PR TITLE
Linux packaging fixes & deployment automation

### PR DESCRIPTION
**Pull request by thomaslepoix**
Hey!

- One doesn't have to care about shared object dependencies, RPM and Debian packagers does that themselves. For Debian, you have to use `CPACK_DEBIAN_PACKAGE_SHLIBDEPS`, for RPM it is automatic.
  Also, except in some rare situations, the `-dev` or `-devel` packages should be buildtime dependencies and not runtime.

- As there is no special dependencies, the same `.rpm` package works for both Fedora and OpenSUSE.

- I added a Github workflow that is triggered by release publications, and that build `.rpm` and `.deb` packages and then deploy those in the release assets. [Here is the result.](https://github.com/thomaslepoix/metashell/releases/tag/v4.0.0)

- The deployment pipeline relies on a Dockerfile that can also be used to build locally and thus could avoid the building process documentation to be outdated or incomplete (one unique entrypoint that does not change and when the process will need to be updated, it will be mendatory to update it)

- (I precise the Ubuntu 20.04 container produce a `.rpm` I tested in Fedora 35 and OpenSUSE tumbleweed containers, and by the way `zypper` seems to currently encounter difficulties to install a package located on the disk, `rpm -i` worked fine; this is not related to the produced package)

### CODE REVIEW

**Comment by sabel83** [comment]
Thank you for the pull request, this looks very interesting but I think it needs some further adjustments. I've tried installing the packages you pointed me to and found the following:

**Ubuntu 20.04, Debian 11.1 and Fedora 35:**
It installed and could start fine but it couldn't load the standard C++ headers (eg. `#include <vector>` failed). This is why I add `dev`/`devel`/`headers` dependencies to the packages.

**OpenSUSE Leap 15.3:**
I could install it with `zypper`, but I got the following error message:
`Problem: nothing 'provides libreadline.so.8()(64bit)' needed by the to be installed metashell-4.0.0-1.x86_64`
It allowed me to continue without that dependency, but `metashell` fails to start without it.

**Comment by thomaslepoix** [comment]
### Dependencies

Oh I didn't get it! Fixed.

### OpenSUSE

It is a normal thing since on Leap `libreadline` is not part of the official repos but the KDE ones. It seems to have been included in Tumbleweed though.
https://pkgs.org/search/?q=libreadline.so.8
It should be fixed by adding the KDE repo with a command like that :

```sh
zypper addrepo https://ftp.lysator.liu.se/pub/opensuse/repositories/KDE:/Frameworks5/openSUSE_Leap_15.3/ kde-frameworks-5-x86_64
```

**Comment by sabel83** [comment]
If you build Metashell on OpenSUSE, it links against `libreadline.so.7`, which is available on a newly installed system, so no extra repo is needed.

**Comment by sabel83** [comment]
I've tested building on OpenSUSE, which still generates a good package. The Ubuntu, Debian and Fedora packages work out of the box. Thank you for the pull request.

**Comment by thomaslepoix** [comment]
I guess if we build on Debian 10 (which uses `libreadline.so.7`) instead of 11, it would work for OpenSUSE Leap. But if you want to support many distrib versions rather than just the current ones, as mentioned here #233, we should use real repositories.

I would suggest to chose [OpenSUSE Build Service](https://build.opensuse.org/) which manages RPM, Debian and also Arch packages (and seems to also support AppImages and Flatpack) in a very automated way : all you have to provide is a `.spec` file for RPM or a source package for Debian and the build matrix is done there, no need to build all the versions in a CI pipeline yourself.

Thank you for PR acceptance.

**Pull request merged**
